### PR TITLE
Upgrade to 2.2.1

### PR DESCRIPTION
**Pull request by andrerom**
Merges in v2.2.1 and handles conflicts. I haven't yet been able to test install as installer crashes, but composer commands pass and so does all composer scripts on install.

### CODE REVIEW

**Comment by kmadejski** [comment]
@andrerom, @damianz5 I've added missing packages to `composer.json` and fixed `ezdesign` issue, but there is an issue regarding improved notifications which I can't solve. 

Table `eznotification` is missing and it has to be added manually to the database on server (https://github.com/ezsystems/ezstudio-notifications/blob/master/bundle/Resources/install/ezstudio-notifications.sql).

**Comment by damianz5** [comment]
`eznotification` is not present in db

**Comment by kmadejski** [comment]
Thanks, @damianz5! Therefore, I think that we can merge it and try to upgrade prod installation. 
WDYT @andrerom / @damianz5?

**Comment by andrerom** [comment]
I have no knowledge about how you do testing and deployments here to be able to answer that question, but :shipit:

**Comment by kmadejski** [comment]
@SylvainGuittard has been always taking care of this before. Any insight from your side, Sylvain? 🙂

**Comment by damianz5** [comment]
retest OK

**Comment by SylvainGuittard** [comment]
Sorry, I did not have time to test it. 
Regarding the last test from @damianz5, I think we can merge it and go live.

**Comment by damianz5** [comment]
Some issues appears, I will handle it, do not merge it yet

**Comment by damianz5** [comment]
retest ok, please merge it

**Comment by damianz5** [comment]
I will add composer.lock in deployment tag

**Pull request merged**
