### PR TITLE
COM-20045: Some bundles appear twice on ezplatform.com

### PR DESCRIPTION
**Pull request by kmadejski**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [COM-20045](https://jira.ez.no/browse/COM-20045)
| **Bug**| yes
| **New feature**    | no

This PR depends on: https://github.com/ezsystems/ezplatform-com/pull/135

Pagination design was changed a little bit as discussed with Nikita.

screen shot 2018-07-23 at 16 43 40
screen shot 2018-07-23 at 16 44 09
screen shot 2018-07-23 at 16 44 18

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
I think it's safer to wait #135 to be merged before merging this PR.
We will be able to see if this new approach works on v2.2.

**Comment by kmadejski** [comment]
@damianz5 since https://github.com/ezsystems/ezplatform-com/pull/135 is merged, can we merge and deploy this one perhaps?

**Comment by damianz5** [comment]
@kmadejski sure, please rebase it to master

**Comment by kmadejski** [comment]
@damianz5 I've rebased to current master. Could you please review again? If everything is all right, please feel to merge it.

**Comment by SylvainGuittard** [comment]
Thanks @kmadejski for your contribution

**Pull request merged**
