### PR TITLE
uniform html attribute formatting and update to documentation link

### PR DESCRIPTION
**Pull request by DavidLiedle**
- Adopts a modern standard for indentation of attributes on separate lines (as used elsewhere in eZ code -- please do not start your review with the words "Please do not..." :) )
- Updates documentation link now that GitHub is used with MarkDown

The link change may be premature, but if we're ready for the new URL to be the primary recommendation, here it is.

### CODE REVIEW

**Comment by DavidLiedle** [comment]
It was, indeed, premature; there's now an official http://doc.ezplatform.com/ which makes this RTD link moot. I'll update this PR.

**Comment by DavidLiedle** [comment]
Ok, I'm content with the doc.ezplatform.com (rather than "docs", plural) after further discussion. :)

**Comment by SylvainGuittard** [comment]
Thanks @DavidLiedle for the contribution.

Regarding the coding standards, it's okay to move the attributes to another line when the line is too long (100-120 characters). In the most recent implementations, the indent is only 1 tab, attributes are not aligned.
Example: https://github.com/ezsystems/hybrid-platform-ui/blob/master/src/bundle/Resources/views/content/tabs/translations.html.twig#L17

Could you please update your PR?

**Comment by DavidLiedle** [comment]
Well, it was worth a try. ;) I'll close, as the main goal of this was to set this as a standard. I think the URL is different again, so I'll do a dedicated PR to that change.

**Comment by DavidLiedle** [comment]
See: https://github.com/ezsystems/ezplatform-com/pull/115

**Pull request closed without merging**
