### PR TITLE
COM-19883: Create a docker container for ezplatform.com

### PR DESCRIPTION
**Pull request by kmadejski**
**JIRA issue**: [https://jira.ez.no/browse/COM-19883](https://jira.ez.no/browse/COM-19883)

### Description

This PR contains modified installation docker environment for ezplatform.com.
To run, follow the procedure explained in doc/docker-compose/README.md, but when run for the first time, run:

``docker-compose -f doc/docker-compose/ezplatform-com_install.yml up --abort-on-container-exit``

instead of:

``docker-compose -f doc/docker-compose/install.yml up --abort-on-container-exit``

Other steps stay unchanged.

### CODE REVIEW

**Comment by andrerom** [comment]
@SylvainGuittard Was something else picked for easing dev install of ezplatform.com? what do you two use for it?

**Comment by SylvainGuittard** [comment]
@andrerom nothing else has been selected so far. I told Kamil to close it because it was old and not a high priority. 
Sébastien wanted also to have ezplatform.com with eZ Launchpad. Developers have different laptop configurations and tools that it will be difficult now to maintain all of those install tools.

I use a virtual machine and I think @damianz5 is not using a particular setup. I don't know about @kmadejski.

**Comment by kmadejski** [comment]
@andrerom @SylvainGuittard I use a virtual machine too ;)

**Comment by andrerom** [comment]
ok, clear :)

**Pull request closed without merging**
