### PR TITLE
#67 : README : add ezplatform.com screenshot

### PR DESCRIPTION
**Pull request by nicolas-bastien**

### CODE REVIEW

**Comment by nicolas-bastien** [comment]
@clash82 ok I understand the image trick ;-)

**Comment by clash82** [comment]
Do we really need a screenshot here? We can just link to a working page? Besides the screenshot is not complete, it only includes part of the screen? how come? :-)

**Comment by nicolas-bastien** [comment]
@SylvainGuittard as we talk about it now, I just wanted to to the same as the demo.

So please just tell me what to you think of it and I'll do.
If you don't want it just close the PR and the issue and it's fine.

**Comment by nicolas-bastien** [comment]
@clash82 if sylvain approuved it I guess you can merge ?

**Comment by clash82** [comment]
> if sylvain approuved it I guess you can merge ?

I'm still not convinced. Please give me some time, I want to discuss it with @SylvainGuittard

**Comment by clash82** [comment]
Closing in favour of #68 (image in full-width added)

**Pull request closed without merging**
