### PR TITLE
COM-19912: Move views to separate file

### PR DESCRIPTION
**Pull request by clash82**
https://jira.ez.no/browse/COM-19912

### CODE REVIEW

**Comment by clash82** [comment]
ping @SylvainGuittard @damianz5

**Comment by damianz5** [comment]
+1

**Comment by SylvainGuittard** [comment]
+1 but we need a jira issue ;)

**Comment by SylvainGuittard** [comment]
Jira issue: https://jira.ez.no/browse/COM-19912

**Comment by clash82** [comment]
Updated.

**Pull request merged**
