### PR TITLE
COM-19949: [Insight] - A Symfony application should be bootable

### PR DESCRIPTION
**Pull request by clash82**
https://jira.ez.no/browse/COM-19949

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
I am not sure to understand the "fix". Could you please give us more details?

**Comment by clash82** [comment]
`composer.lock` was not updated, we have to change our flow of updating ezplatform - more details on daily next week.

**Comment by clash82** [comment]
ping @damianz5

**Comment by damianz5** [comment]
+1

**Pull request merged**
